
#ifndef _XMEFFECTS_H_
#define _XMEFFECTS_H_

// XM-file: racers - green flag.xm

#undef  FMUSIC_XM_INSTRUMENTVIBRATO_ACTIVE
#undef  FMUSIC_XM_VOLUMEENVELOPE_ACTIVE
#define FMUSIC_XM_PANENVELOPE_ACTIVE
#define FMUSIC_XM_VOLUMEBYTE_ACTIVE
#undef  FMUSIC_XM_AMIGAPERIODS_ACTIVE
#define FMUSIC_XM_ARPEGGIO_ACTIVE
#undef  FMUSIC_XM_PORTAUP_ACTIVE
#define FMUSIC_XM_PORTADOWN_ACTIVE
#undef  FMUSIC_XM_PORTATO_ACTIVE
#undef  FMUSIC_XM_VIBRATO_ACTIVE
#undef  FMUSIC_XM_PORTATOVOLSLIDE_ACTIVE
#undef  FMUSIC_XM_VIBRATOVOLSLIDE_ACTIVE
#undef  FMUSIC_XM_TREMOLO_ACTIVE
#undef  FMUSIC_XM_SETPANPOSITION_ACTIVE
#undef  FMUSIC_XM_SETSAMPLEOFFSET_ACTIVE
#define FMUSIC_XM_VOLUMESLIDE_ACTIVE
#undef  FMUSIC_XM_PATTERNJUMP_ACTIVE
#undef  FMUSIC_XM_SETVOLUME_ACTIVE
#undef  FMUSIC_XM_PATTERNBREAK_ACTIVE
#define FMUSIC_XM_SETSPEED_ACTIVE
#undef  FMUSIC_XM_SETGLOBALVOLUME_ACTIVE
#undef  FMUSIC_XM_GLOBALVOLSLIDE_ACTIVE
#undef  FMUSIC_XM_KEYOFF_ACTIVE
#undef  FMUSIC_XM_SETENVELOPEPOS_ACTIVE
#undef  FMUSIC_XM_PANSLIDE_ACTIVE
#undef  FMUSIC_XM_MULTIRETRIG_ACTIVE
#undef  FMUSIC_XM_TREMOR_ACTIVE
#undef  FMUSIC_XM_EXTRAFINEPORTA_ACTIVE
#undef  FMUSIC_XM_FINEPORTAUP_ACTIVE
#undef  FMUSIC_XM_FINEPORTADOWN_ACTIVE
#undef  FMUSIC_XM_SETVIBRATOWAVE_ACTIVE
#undef  FMUSIC_XM_SETFINETUNE_ACTIVE
#undef  FMUSIC_XM_PATTERNLOOP_ACTIVE
#undef  FMUSIC_XM_SETTREMOLOWAVE_ACTIVE
#undef  FMUSIC_XM_SETPANPOSITION16_ACTIVE
#undef  FMUSIC_XM_RETRIG_ACTIVE
#undef  FMUSIC_XM_FINEVOLUMESLIDEUP_ACTIVE
#undef  FMUSIC_XM_FINEVOLUMESLIDEDOWN_ACTIVE
#undef  FMUSIC_XM_NOTECUT_ACTIVE
#undef  FMUSIC_XM_NOTEDELAY_ACTIVE
#undef  FMUSIC_XM_PATTERNDELAY_ACTIVE

#endif
